#!/bin/bash --rcfile

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -f ~/.bashrc ]
then
	. ~/.bashrc
fi

export PATH="$DIR/bin:$PATH"
export PYTHONPATH="$DIR/lib/python2.7:$PYTHONPATH"

if [ ! -d "$DIR/.venv" ]
then
	virtualenv "$DIR/.venv"
fi

. "$DIR/.venv/bin/activate"

PS1="($DIR) $_OLD_VIRTUAL_PS1"

if [ -f "$DIR/.localrc" ]
then
	. "$DIR/.localrc"
fi
