#!/bin/bash --rcfile
# Copyright 2017 Queue Continuum LLC

venv_update () {
	if [ ! -f "$VENV_BASEDIR/.venv/.requirements.txt.d" -o "$VENV_BASEDIR/requirements.txt" -nt "$VENV_BASEDIR/.venv/.requirements.txt.d" ]
	then
		virtualenv --clear "$VENV_BASEDIR/.venv"
		pip install -r "$VENV_BASEDIR/requirements.txt"
		touch "$VENV_BASEDIR/.venv/.requirements.txt.d"
	fi
	return 0
}

VENV_BASEDIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ -f ~/.bashrc ]
then
	. ~/.bashrc
fi
# TODO on Debian, /etc/bash.bashrc is sourced as well

if [ -z ${PATH+x} ]
then
	export PATH="$VENV_BASEDIR/bin"
else
	export PATH="$VENV_BASEDIR/bin:$PATH"
fi

if [ -z ${PYTHONPATH+x} ]
then
	export PYTHONPATH="$VENV_BASEDIR/lib/python2.7"
else
	export PYTHONPATH="$VENV_BASEDIR/lib/python2.7:$PYTHONPATH"
fi

if [ ! -d "$VENV_BASEDIR/.venv" ]
then
	virtualenv "$VENV_BASEDIR/.venv"
fi

VENV_OLD_PS1="$PS1"

. "$VENV_BASEDIR/.venv/bin/activate"

if [ ! "$VIRTUAL_ENV" -ef "$VENV_BASEDIR/.venv" ]
then
	echo "Unexpected Python virtual environment."
	exit 1
fi

venv_update

if [ -f "$VENV_BASEDIR/.venvrc" ]
then
	. "$VENV_BASEDIR/.venvrc"
fi

if [ -z ${VENV_NAME+x} ]
then
	VENV_NAME="$VENV_BASEDIR"
fi

PS1="($VENV_NAME) $VENV_OLD_PS1"
